theme: jekyll-theme-minimal
title: Yichen Gao
markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      stylesheet: /assets/css/style.css
